# DeepSource is a code quality analyser that runs on our GitHub PRs
# https://deepsource.io/gh/signaux-faibles/prepare-import

version = 1

test_patterns = ["*_test.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/signaux-faibles/prepare-import"

[[analyzers]]
name = "test-coverage"
enabled = true
