name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev, dev-finalisation]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # for deepsource, cf https://deepsource.io/docs/how-to/add-go-cov-ci.html#with-github-actions
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v .

      - name: Check formatting
        run: |
          make format format-doc
          exit $(git diff | wc -l) # Return a non-zero error code if any output file has changed

      - name: Install test dependencies
        run: |
          sudo apt-get install -y ssconvert # for filter_to_diane

      - name: Test
        run: go test ./... -v -coverprofile=coverage.out

      - name: Upload coverage to codacy
        run: |
          go get github.com/schrej/godacov
          go run github.com/schrej/godacov -t ${{ secrets.CODACY_REPOSITORY_TOKEN_FOR_COVERAGE }} -r ./coverage.out -c $GITHUB_SHA

      - name: Upload coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN_FOR_COVERAGE }}
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key go --value-file ./coverage.out
