name: Go

on:
    push:
        branches:
    release:
        types: [published, edited]
    pull_request:
        branches:
            - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v3
        with:
          go-version: 1.14
        id: go

#      - name: Set up Python2 (for goupy)
#        uses: actions/setup-python@v4
#        with:
#          python-version: 2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          # for deepsource, cf https://deepsource.io/docs/how-to/add-go-cov-ci.html#with-github-actions
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v .

      - name: Check formatting
        run: |
          make format format-doc
          exit $(git diff | wc -l) # Return a non-zero error code if any output file has changed

      - name: Install test dependencies
        run: |
          sudo apt-get install -y --no-install-recommends gnumeric # more specifically: "ssconvert", for filter_to_diane

      - name: Test
        run: go test ./... -v -coverprofile=coverage.out

      - name: Upload coverage to codacy
        run: |
          go get github.com/schrej/godacov
          go run github.com/schrej/godacov -t ${{ secrets.CODACY_REPOSITORY_TOKEN_FOR_COVERAGE }} -r ./coverage.out -c $GITHUB_SHA

      - name: Upload coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN_FOR_COVERAGE }}
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key go --value-file ./coverage.out

  publish:
    name: Push OpenSignauxFaibles container
    runs-on: ubuntu-latest
    steps:

#      - name: Check out code
#        uses: actions/checkout@v3
#
#      - name: Set up node
#        uses: actions/setup-node@v2
#        with:
#            node-version: 12
#
#      - name: Set up Go 1.14
#        uses: actions/setup-go@v3
#        with:
#            go-version: 1.1
      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=sha
          flavor: |
            latest=false
            suffix=-${{ matrix.env }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./build-container
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}